#!/bin/bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FCA=$GOPATH/src/caserver

echo "Running integration tests ..."

export PATH=$PATH:$GOPATH/bin

go get github.com/axw/gocov/...
go get github.com/AlekSi/gocov-xml

PKGS=`go list caserver/test/integration/...`

go test $PKGS

exit $?
